sudo: false

language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23

cache:
 directories:
 - $HOME/.m2/repository

jdk:
 - oraclejdk8

script: 
 - mkdir -p $HOME/.m2/repository/com/android/support/cardview-v7/23.4.0
 - cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/cardview-v7/23.4.0/* $HOME/.m2/repository/com/android/support/cardview-v7/23.4.0
 - mkdir -p $HOME/.m2/repository/com/android/support/animated-vector-drawable/23.4.0
 - cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/animated-vector-drawable/23.4.0/* $HOME/.m2/repository/com/android/support/animated-vector-drawable/23.4.0
 - mkdir -p $HOME/.m2/repository/com/android/support/support-vector-drawable/23.4.0
 - cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-vector-drawable/23.4.0/* $HOME/.m2/repository/com/android/support/support-vector-drawable/23.4.0
 - mkdir -p $HOME/.m2/repository/com/android/support/support-annotations/23.4.0
 - cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-annotations/23.4.0/* $HOME/.m2/repository/com/android/support/support-annotations/23.4.0
 - mkdir -p $HOME/.m2/repository/com/android/support/recyclerview-v7/23.4.0
 - cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.4.0/* $HOME/.m2/repository/com/android/support/recyclerview-v7/23.4.0
 - mkdir -p $HOME/.m2/repository/com/android/support/design/23.4.0
 - cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/design/23.4.0/* $HOME/.m2/repository/com/android/support/design/23.4.0
 - mkdir -p $HOME/.m2/repository/com/android/support/support-v4/23.4.0
 - cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/* $HOME/.m2/repository/com/android/support/support-v4/23.4.0
 - mkdir -p $HOME/.m2/repository/com/android/support/appcompat-v7/23.4.0
 - cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.4.0/* $HOME/.m2/repository/com/android/support/appcompat-v7/23.4.0
 - echo "$P12_BASE64" | base64 -d > ../libe.p12
 - echo "KEYSTORE_BASE64" | base64 -d > ../libe.keystore
 - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report -DrepoToken=$COVERALLS_TOKEN android:zipalign android:publish-apk -Ppublisher -Dsecret.storepass=$SECRET_STOREPASS -Dsecret.keypass=$SECRET_KEYPASS
