sudo: false

language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23

cache:
 directories:
 - $HOME/.m2/repository

jdk:
 - oraclejdk8

script: 
 - mkdir target
 - cd target
 - git clone git://github.com/libetl/maven-android-sdk-deployer.git maven-android-sdk-deployer
 - cd maven-android-sdk-deployer
 - mvn install -pl extras/compatibility-v4,extras/compatibility-v7-appcompat,extras/compatibility-v7-recyclerview,extras/design -Dextras.compatibility.v4.groupid=com.android.support -Dextras.compatibility.v4.artifactid=support-v4 -Dextras.compatibility.v7.appcompat.groupid=com.android.support -Dextras.compatibility.v7.appcompat.artifactid=appcompat-v7 -Dextras.compatibility.v7.recyclerview.groupid=com.android.support -Dextras.compatibility.v7.recyclerview.artifactid=recyclerview-v7 -Dextras.design.groupid=com.android.support -Dextras.design.artifactid=design -DPkg.Revision=23.4.0
 - cd ../../
 - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report -DrepoToken=$COVERALLS_TOKEN
