sudo: false
language: android
android:
  components:
  - build-tools-25.0.0
  - android-25
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-25
cache:
  directories:
  - /usr/local/android-sdk
  - "$HOME/.m2/repository"
git:
  depth: 65536 
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_23480f79020f_key -iv $encrypted_23480f79020f_iv -in libe.b64.enc -out ../libe.b64 -d
- cat ../libe.b64 | sed -e '/==/q' | base64 -d > ../libe.p12
- cat ../libe.b64 | sed -e '1,/==/d' | base64 -d > ../libe.keystore
- mkdir -p $HOME/.m2/repository/com/android/support/cardview-v7/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/cardview-v7/25.0.0/*
  $HOME/.m2/repository/com/android/support/cardview-v7/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/animated-vector-drawable/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/animated-vector-drawable/25.0.0/*
  $HOME/.m2/repository/com/android/support/animated-vector-drawable/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/support-vector-drawable/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-vector-drawable/25.0.0/*
  $HOME/.m2/repository/com/android/support/support-vector-drawable/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/support-annotations/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-annotations/25.0.0/*
  $HOME/.m2/repository/com/android/support/support-annotations/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/recyclerview-v7/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/25.0.0/*
  $HOME/.m2/repository/com/android/support/recyclerview-v7/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/design/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/design/25.0.0/*
  $HOME/.m2/repository/com/android/support/design/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/support-v4/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-v4/25.0.0/*
  $HOME/.m2/repository/com/android/support/support-v4/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/appcompat-v7/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/25.0.0/*
  $HOME/.m2/repository/com/android/support/appcompat-v7/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/support-compat/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-compat/25.0.0/*
  $HOME/.m2/repository/com/android/support/support-compat/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/support-media-compat/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-media-compat/25.0.0/*
  $HOME/.m2/repository/com/android/support/support-media-compat/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/support-core-utils/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-core-utils/25.0.0/*
  $HOME/.m2/repository/com/android/support/support-core-utils/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/support-core-ui/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-core-ui/25.0.0/*
  $HOME/.m2/repository/com/android/support/support-core-ui/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/support-fragment/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/support-fragment/25.0.0/*
  $HOME/.m2/repository/com/android/support/support-fragment/25.0.0
- mkdir -p $HOME/.m2/repository/com/android/support/transition/25.0.0
- cp /usr/local/android-sdk/extras/android/m2repository/com/android/support/transition/25.0.0/*
  $HOME/.m2/repository/com/android/support/transition/25.0.0
script:
- mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report
  org.eluder.coveralls:coveralls-maven-plugin:report -DrepoToken=$COVERALLS_TOKEN android:manifest-merger
  install android:zipalign android:publish-apk -Ppublisher -Dsecret.storepass=$SECRET_STOREPASS
  -Dsecret.keypass=$SECRET_KEYPASS -Dandroid.manifestMerger.versionCode=$(git rev-list --no-merges --count HEAD)
  -Dandroid.publisher.track=$TRAVIS_BRANCH -Ddestination.manifestFile=AndroidManifest.xml
